int main()
{
    // Initialize Vulkan ...

    // Create semaphores ...
    // Crate graphics command pool ...
    // Create command buffer and fence ...
    // Create render pass ...

    bool isApplicationRunning = true;
    while (isApplicationRunning)
    {
        // Process window messages ...

        // Acquire a swapchain image ...
        // Wait for the previous commands to finish ...
        // Create a framebuffer ...
        // Record rendering commands ...
        // Submit rendering commands ...
        // Present ...
    }

    // Cleanup ...

    return 0;
}
