void CreateVertexBuffer(...)
{
    // Create staging buffer ...
    // Upload vertex data to the staging buffer ...
    // Create vertex buffer ...
    // Issue a copy command to our GPU for copying
    // data from our staging buffer to our vertex buffer ...
    // Wait for the copy to finish ...
    // Cleanup ...
}
