void CreateVertexBuffer(...)
{
    // Create staging buffer ...
    // Upload vertex data to the staging buffer ...
    // Create vertex buffer ...
    // Issue a copy command ...
    // Wait for the copy to finish ...
    // Cleanup ...
}
