int main()
{
    // Create Vulkan instance and debug messenger ...
    // Create window ...
    // Create presentation surface ...
    // Pick physical device ...
    // Create logical device ...
    // Create swapchain ...

    bool isApplicationRunning = true;
    while (isApplicationRunning)
    {
        // Process window messages ...
    }

    // Cleanup ...

    return 0;
}
