int main(void)
{
    // Setup floor entity ...
    // Setup cube entity ...
    // Setup light entity ...
    // Setup camera ...

    while (isApplicationRunning)
    {
        // Update entities ...
        // Render entities ...
    }
}
